Respond with 200 OK to resources request.
4teamwork/ftw.maintenanceserver pull request #8
Opened 2017-11-22 16:11 UTC by njohner

We now respond with 200 OK when we send a local resource back.
Also added a test to check that we indeed respond 200 for resources.

2017-11-22 16:11 UTC, njohner commented
Tests should fail because of a missing dependency in ftw.testbrowser. I fixed that in https://github.com/4teamwork/ftw.testbrowser/pull/79

2017-11-22 17:45 UTC, jone requested changes

2017-11-22 17:45 UTC, jone commented on ftw/maintenanceserver/server.py
> +            self.is_resource=False
As of pep8, please add some spaces around the equal sign.

2017-11-23 09:28 UTC, njohner commented
sorry, done!

2017-11-27 18:06 UTC, jone approved these changes
Thank you very much 👍 
Please merge and cut a release (`1.2.0`) 🎉

2017-11-28 07:56 UTC, merged

2017-11-28 08:22 UTC, njohner commented
Oh no, sorry, wrong version number

2017-11-28 11:18 UTC, jone commented
No worries, this change can be considered a bugfix...

2018-01-03 09:09 UTC, njohner commented
Closed #6